db_file: C:\Program Files\ResortLock3.7\iKeypadLockDB.mdb
export_directory: C:\Users\Darren\Documents\Excel\resortlock-import-export
filename_prefix: user_code_
ignore_these_locks:
  - Music - Practice 1